import { QrTemplate } from '../types/qr';

export const FEATURED_TEMPLATES: QrTemplate[] = [
  {
    id: 'template-ocean-gradient',
    name: 'Ocean Horizon',
    description: 'Deep navy to electric sky gradient with rounded modules and classic finder.',
    category: 'Popular',
    glowColor: 'rgba(79, 163, 255, 0.18)',
    config: {
      style: 'ROUNDED',
      colorMode: 'LINEAR_GRADIENT',
      startColor: '#035081',
      endColor: '#4FA3FF',
      finderStyle: 'ROUNDED',
      backgroundColor: '#FFFFFF',
      backgroundOpacity: 1,
      frameStyle: 'NONE',
    },
  },
  {
    id: 'template-golden-luxury',
    name: 'Compass Gold',
    description: 'Rich amber accent framing with modern apertures and dark contrast.',
    category: 'Business',
    glowColor: 'rgba(248, 180, 68, 0.18)',
    config: {
      style: 'SQUARE',
      colorMode: 'SOLID',
      foregroundColor: '#F8B444',
      backgroundColor: '#0F172A',
      backgroundOpacity: 1,
      finderStyle: 'MODERN_FRAME',
      frameStyle: 'GLASS_PLATE',
      frameCaptionText: 'SCAN ME',
    },
  },
  {
    id: 'template-cyber-halftone',
    name: 'Modern Halftone',
    description: 'Dynamic dot density modules with circular finder rings for tech startups.',
    category: 'Creative',
    glowColor: 'rgba(168, 85, 247, 0.18)',
    config: {
      style: 'HALFTONE',
      colorMode: 'RADIAL_GRADIENT',
      startColor: '#4FA3FF',
      endColor: '#035081',
      finderStyle: 'CIRCLE',
      backgroundColor: '#0A1420',
      backgroundOpacity: 1,
      frameStyle: 'NONE',
    },
  },
  {
    id: 'template-instagram-card',
    name: 'Social Aperture',
    description: 'Camera aperture frame with instagram style finders and high visibility.',
    category: 'Tech',
    glowColor: 'rgba(236, 72, 153, 0.18)',
    config: {
      style: 'ROUNDED',
      colorMode: 'LINEAR_GRADIENT',
      startColor: '#7C3AED',
      endColor: '#EC4899',
      finderStyle: 'INSTAGRAM',
      frameStyle: 'SCAN_ME_CARD',
      frameCaptionText: 'SCAN ME',
    },
  },
  {
    id: 'template-glassmorphism',
    name: 'Frosted Glass',
    description: 'Subtle semitransparent glass modules with star pattern background.',
    category: 'Creative',
    glowColor: 'rgba(56, 189, 248, 0.18)',
    config: {
      style: 'ROUNDED',
      colorMode: 'SOLID',
      foregroundColor: '#035081',
      backgroundColor: '#FFFFFF',
      backgroundOpacity: 0,
      frameStyle: 'GLASS_PLATE',
      frameCaptionText: 'SCAN ME',
    },
  },
  {
    id: 'template-executive-minimal',
    name: 'Executive Minimal',
    description: 'Ultra sharp square geometry designed for enterprise business print materials.',
    category: 'Minimal',
    glowColor: 'rgba(148, 163, 184, 0.14)',
    config: {
      style: 'SQUARE',
      colorMode: 'SOLID',
      foregroundColor: '#111827',
      backgroundColor: '#FFFFFF',
      backgroundOpacity: 1,
      finderStyle: 'CLASSIC',
      frameStyle: 'NONE',
    },
  },
];
